server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: user-service

management:
  endpoints:
    web:
      exposure:
        include: refresh,health

logging:
  level:
    root: DEBUG
