services:
  config-server:
    build: ./config_server
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config-repo:ro
    environment:
      - SPRING_PROFILES_ACTIVE=native
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 2

  gateway-service:
    build: ./gateway_service
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888

  user-service:
    build: ./user_service
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
