# spring.application.name=user_service
# server.port=8081
# spring.config.import=optional:configserver:http://localhost:8888
# management.endpoints.web.exposure.include=refresh
# spring.cloud.config.enabled=false
# spring.cloud.compatibility-verifier.enabled=false
spring.config.import=optional:configserver:http://config-server:8888
