spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:/config_service
        # git:
        #   uri: https://github.com/vandan1729/Neuronet
        #   search-paths: config_server