spring.application.name=config_server
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///config-repo
